

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - Path=/employees/**
          - id: department-service
            uri: lb://department-service
            predicates:
              - Path=/departments/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info
server:
  port: 8060
